// This file is auto-generated by packages/ripple-ui/scripts/generate-deep-types.mjs
export { AccessoryButton as default } from "../index.js";
export type { AccessoryButtonProps } from "../index.js";
