// This file is auto-generated by packages/ripple-ui/scripts/generate-deep-types.mjs
export { BarChart as default } from "../index.js";
export type { BarChartDatum, BarChartProps } from "../index.js";
