// This file is auto-generated by packages/ripple-ui/scripts/generate-deep-types.mjs
export { LoadingCompleteView as default } from "../index.js";
export type { LoadingCompleteViewProps } from "../index.js";
